// Generated by CoffeeScript 1.7.1
(function() {
  FlappyBug.MAIN = METHOD({
    run: function() {
      FlappyBug.MATCH_VIEW({
        uris: [''],
        target: FlappyBug.HomeView
      });
      FlappyBug.MATCH_VIEW({
        uris: ['Game'],
        target: FlappyBug.GameView
      });
      return FlappyBug.MATCH_VIEW({
        uris: ['Restart'],
        target: CLASS({
          preset: function() {
            return VIEW;
          },
          init: function(cls, inner, self) {
            return FlappyBug.GO('Game');
          }
        })
      });
    }
  });

}).call(this);
